# Generated by Django 5.2.13 on 2026-04-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfig',
            name='min_booking_notice_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
