# Generated by Django 5.2.13 on 2026-04-21 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('bio', models.CharField(blank=True, default='', max_length=300)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('specialties', models.JSONField(blank=True, default=list, help_text='Lista de especialidades como etiquetas.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barber_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Barbero',
                'verbose_name_plural': 'Barberos',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='BarberSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.SmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_start', models.TimeField(blank=True, help_text='Hora de inicio del descanso (ej. 14:00).', null=True)),
                ('break_end', models.TimeField(blank=True, help_text='Hora de fin del descanso (ej. 15:00).', null=True)),
                ('is_working', models.BooleanField(default=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='barbers.barber')),
            ],
            options={
                'verbose_name': 'Horario de Barbero',
                'verbose_name_plural': 'Horarios de Barberos',
                'ordering': ['day_of_week'],
                'unique_together': {('barber', 'day_of_week')},
            },
        ),
    ]
